### ISSUE TITLE
Rpi_adc_stream utility

### ISSUE THREAD

**Issue by noeldum** [jbentham/rpi#3]
In this article below you mention a utility called rpi_adc_stream which i can't find anywhere.
https://iosoft.blog/2020/11/16/streaming-analog-data-raspberry-pi/

There is a gihub link but it points to your profile only. In the rpi section the utility is not there. 

Could you help? This utility will help me a lot. Thanks in advance.

**Comment by jbentham** [comment]
The files are in the 'streaming' project directory; I've modified the 
post to make that clear.

**Comment by noeldum** [comment]
Thanks a lot. Found it now. 
I plan to use this with a mcp3208 which has 8 channels instead of 2. I hope the code will cope with options like -I 3 or -I 8.

**Comment by jbentham** [comment]
Not without mods; you'll need to change the SPI transmit data, but the 
code for the receiver & pacing might be OK as-is.

**Comment by noeldum** [comment]
Thanks a lot. Found it now. 
I plan to use this with a mcp3208 which has 8 channels instead of 2. I hope the code will cope with options like -I 3 or -I 8.
