### ISSUE TITLE
Direct buffer manipulation?

### ISSUE THREAD

**Issue by psy0rz** [jbentham/rpi#9]
(i know you're busy so this is not a feature request)

I'm planning to run a bunch of ws2812 matrix-displays at 60fps.

Would it be more efficient to directly manipulate the DMA buffer instead of using a memcpy? Usually i'm only updating a small percentage of the pixels each frame.

Offcourse you would need 2 buffers and switch between them to not distrub the one that is currently transmitted.

Ill try to transform you code into something that can be used in a nodejs module. (e.g. no more hardcoded defines needed)

**Comment by jbentham** [comment]
Yes, it can be much more efficient, but you may well run into problems 
with data caching. This applies to the both the display data and the DMA 
control blocks; there can be all sorts of strange problems, caused by 
the DMA controller getting an arbitrary mix of old & new values.

**Comment by psy0rz** [comment]
Well your testcode uses only 10% CPU at an RPI3 with 8x256 leds, so thats already extremely good compared to the other libraries. I'll try not to optimize too early, and fix other stuff first.

**Comment by petiepooo** [comment]
Donald Knuth wrote:
>"Premature optimization is the root of all evil."

😄

**Comment by psy0rz** [comment]
WIP https://github.com/psy0rz/rpi-ws281x-smi
